# docker-compose.yml

version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - mysql
      - redis
    networks:
      - local-network
    env_file:
      - .env
  mysql:
    container_name: ${APP_NAME}_mysql_container
    image: mysql
    restart: 'no'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cake-pals-db
    ports:
      - '3308:3306'
    networks:
      - local-network
    volumes:
      - mysql-data:/var/lib/cake-pals-db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${APP_NAME}_phpmyadmin_container
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - '8080:80'
    depends_on:
      - mysql
    networks:
      - local-network

  redis:
    container_name: ${APP_NAME}_redis_container
    image: redis:latest
    restart: 'no'
    ports:
      - '6379:6379'
    networks:
      - local-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: ${APP_NAME}_commander_container
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=12345
    ports:
      - '8081:8081'
    depends_on:
      - redis
    networks:
      - local-network

volumes:
  mysql-data:
networks:
  local-network:
